### ISSUE TITLE
Fork multi user macro reusability / reconfigurability

### ISSUE THREAD

**Issue by Phoscur** [Phoscur/oryx-macro-hax#2]
Following up on https://github.com/gittyeric/ergodox-macro-hax/issues/7
We need to stop comment out eachothers macros.

I want to refactor 
- extract my-macros.ts per user `macros/<username>` - add feature flags to enable loading multiple macro collections
- move macros.ts into `src` folder

**Comment by Phoscur** [comment]
@sytone please check this out!
Do we want to go for TypeScript Strict Mode too?

**Comment by sytone** [comment]
Pulling it today to have a look, I see typescript is not happy with the unsafe assignments, a refactor to classes and interfaces would clean that up if you want to go to strict.

**Comment by Phoscur** [comment]
You are reading my mind :) There is also missing tests for some special parts:
![grafik](https://user-images.githubusercontent.com/191093/231840628-102ed16e-7de7-4496-83e6-c8afe2632ca5.png)
