### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by DeepSky8** [Phoscur/oryx-macro-hax#7]
I think I'm failing to update the .env file correctly.

I copied the text in the provided .env.dist file into a new file I named 'process.env', and confirmed that it is a file of type .env. I've updated it with my information, as follows:

```
USER_NAME="DeepSky8"
LAYOUT_ID="0LXoN"
LAYOUT_FOLDER="moonlander_qwerty-js_source"
LAYOUT_SRC="./layout_src"
```

--

When I run 
`npm run get -- 0LXoN`

I receive the following update and error: 

Downloaded layout "0LXoN" to ./layout_src (from https://oryx.zsa.io/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTAxUUE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb15af0be4346b3ef05dc6d4b34036ec6d80b9ad/moonlander_qwerty-js_0LXoN_Jyz49.zip).

TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:400:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:429:7)
    at C:\Users\Joel\qmk_firmware\ergodox-macro-hax\src\oryx-downloader.ts:53:29

Could you offer some insight what I'm failing to do correctly?

Thanks!

**Comment by Phoscur** [comment]
Hi! (sorry just noticed I have to follow my own repo or something - I did not get a notification)
> LAYOUT_FOLDER="moonlander_qwerty-js_source"
> LAYOUT_SRC="./layout_src"
This is the right configuration, so I am unsure why it breaks for you in L53 (this is where it joins those path strings to extract the folder).

I am using Node18 on Windows, what's your environment?
```
C:\Users\Phoscur\qmk_firmware\keyboards\moonlander\ergodox-macro-hax>npm run get -- 0LXoN

> oryx-macro-hax@2.0.0 get
> ts-node -r dotenv/config src/oryx-downloader.ts 0LXoN

Downloaded layout "0LXoN" to ./layout_src (from https://oryx.zsa.io/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTAxUUE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb15af0be4346b3ef05dc6d4b34036ec6d80b9ad/moonlander_qwerty-js_0LXoN_Jyz49.zip).
Unpacked folder: moonlander_qwerty-js_source
```

**Comment by Phoscur** [comment]
Update: #8 will derive the folder name from the layout title & geometry!
You can already try it, it should be already better in advising you about the correct configuration!

**Comment by Phoscur** [comment]
> I copied the text in the provided .env.dist file into a new file I named 'process.env', and confirmed that it is a file of type .env.

@DeepSky8 found your mistake after reading your issue again - here is the solution:

The filename has to be `.env` not `process.env`!

Maybe I can get rid of the `dotenv` dependency and this difficulty¹ with `yargs` & `node-persist` watch my progress in #8!

¹on Windows Explorer might not let you do the renaming to "just a filename extension", I'd recommend using VSCode.
